config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do 
      put :change
    end
  end
  
  devise_for :users
  resources :posts
  get 'home/index'
  
  get 'about' => 'home#about'  
  get 'test' => 'home#test'

  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
    
end

app/models/task.rb
class Task < ActiveRecord::Base
    belongs_to :user
    
    auto_html_for :content do
		html_escape
		image
		youtube(:width => "100%", :height => 250, :autoplay => false)
		link :target => "_blank", :rel => "nofollow"
		simple_format
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks, dependent: :destroy      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to tasks_path
    end
  end
  
  def about 
  end
  
  def test
  end 
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :autor, :body, :url, :tag)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change]
  before_action :authenticate_user!

  # GET /tasks
  # GET /tasks.json
  def index
    @to_do = current_user.tasks.where(state:'to_do')
    @doing = current_user.tasks.where(state:'doing')
    @done  = current_user.tasks.where(state:'done')
    @task = Task.new
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
        @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
        format.js
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end
  
  def change
    @task.update_attributes(state: params[:state])
    respond_to do |format| 
      format.html { redirect_to tasks_path, notice: "Task status successfully changed"}
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :state)
    end
end
0

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_text.html.erb
<p>
Grid systems are used for creating page layouts through a series of rows and columns that house your content. Here's how the Bootstrap grid system works:

Rows must be placed within a .container (fixed-width) or .container-fluid (full-width) for proper alignment and padding.
Use rows to create horizontal groups of columns.
Content should be placed within columns, and only columns may be immediate children of rows.
Predefined grid classes like .row and .col-xs-4 are available for quickly making grid layouts. Less mixins can also be used for more semantic layouts.
Columns create gutters (gaps between column content) via padding. That padding is offset in rows for the first and last column via negative margin on .rows.
The negative margin is why the examples below are outdented. It's so that content within grid columns is lined up with non-grid content.
Grid columns are created by specifying the number of twelve available columns you wish to span. For example, three equal columns would use three .col-xs-4.
If more than 12 columns are placed within a single row, each group of extra columns will, as one unit, wrap onto a new line.
Grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes, and override grid classes targeted at smaller devices. Therefore, e.g. applying any .col-md-* class to an element will not only affect its styling on medium devices but also on large devices if a .col-lg-* class is not present.
Look to the examples for applying these principles to your code.
</p>

app/views/home/about.html.erb
<h1>About Ruby on Rails</h1>
<p> Ruby on rails é framework mais rápido para aplicação web, utiliza MVC  </p>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1><i class="fa fa-circle-o-notch"></i> Tarefas</h1>
  <p>Aplicativo de tarefa, com Framwork Ruby on Rails</p>
  <%=link_to 'Sign up', new_user_registration_path, class:"btn btn-primary btn-lg" %>
</div>

app/views/home/test.html.erb
<div class="row">
    <div class="col-md-4">
        <h1 class="text-center">To do</h1>
        <div class="panel panel-info">
            <div class="panel-heading">My Todo</div>
            <div class="panel-body">Need to update this</div>
            <div class="panel-footer text-center">doing</div>
        </div>
    </div>
    <div class="col-md-4">
        <h1 class="text-center">Doing</h1>
        <div class="panel panel-info">
            <div class="panel-heading">Doing</div>
            <div class="panel-body">Need to update this</div>
            <div class="panel-footer text-center">change state</div>
        </div>
    </div>
    <div class="col-md-4">
        <h1 class="text-center">Done</h1>
        <div class="panel panel-info">
            <div class="panel-heading">Done</div>
            <div class="panel-body">Need to update this</div>
            <div class="panel-footer text-center">Change state</div>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<i class='fa fa-circle-o-notch'></i> SENAI".html_safe, root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li> <%= link_to 'Edit Profile', edit_user_registration_path  %></li>
          <li> <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li> <%= link_to 'About', about_path %></li>
          <li> <%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Workspace</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
  
<div class="container">
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
  <%= yield %>  
</div>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Autor</th>
      <th>Body</th>
      <th>Url</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.titulo %></td>
        <td><%= post.autor %></td>
        <td><%= post.body %></td>
        <td><%= post.url %></td>
        <td><%= post.tag %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @post.titulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @post.autor %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @post.tag %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task, html: { class:'form-signin'}  ) do |f| %>
  <%= f.error_notification %>

    <%= f.input :content, required: true, label: false, autofocus: true, placeholder: "Content", input_html: {class: 'form-control'} %>
  
    <%= f.button :submit, class:"btn btn-primary btn-lg btn-block" %>
  
<% end %>

app/views/tasks/_task.html.erb
<div id="task_<%= task.id %>">

<div class="panel panel-info">
    <div class="panel-heading">
        <!--<i class="fa fa-pencil" aria-hidden="true"></i>-->
         <!--<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myupdatetask_<%= task.id %>">-->
        <%= link_to edit_task_path(task), id:"myupdatetask_#{task.id}" do %>
            Created <%= time_ago_in_words(task.created_at) %> ago 
        <% end %>
        <%= link_to 'X', task_path(task), method: :delete, remote: true , class:"pull-right"  %>
    </div>
  <div class="panel-body"><%= raw(task.content_html) %></div>

    <div class="panel-footer text-center">
        <div class="btn-group btn-group-justified">
            <% if task.state == 'doing' %>
              <%= link_to "<i class ='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "to_do"), method: :put, class: "btn btn-info btn-md btn-block" %>
	          <%= link_to "<i class ='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "done"), method: :put, class: "btn btn-info btn-md btn-block" %>
	        <% elsif task.state == 'done' %>
	           <%= link_to "<i class ='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "doing"), method: :put, class: "btn btn-info btn-md btn-block" %>
            <% else %>
	          <%= link_to "<i class ='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "doing"), method: :put, class: "btn btn-info btn-md btn-block" %>
            <% end %>
        </div>
    </div>
</div>
</div>



           <!-- Modal -->
          <%= simple_form_for(task, :method => :put, remote: true) do |f| %>
            <div class="modal fade" id="myupdatetask_<%= task.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                     <h4 class="modal-title" id="myModalLabel">Update Post</h4>
                  </div>
                  <div class="modal-body">
                    <div class="field">
                      <%= f.input :content, required: true, label: false, autofocus: true, placeholder: "Content", input_html: {class: 'form-control'} %>
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <%= submit_tag "Create", class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
            </div>
<% end %>
 

app/views/tasks/create.js.erb
$("#mynewpost").modal('hide');
$(".task_content").val('');
$("#container_tasks").prepend('<%= j render @task %>');
$("#task_<%= @task.id %>").hide().fadeIn(1000);

app/views/tasks/destroy.js.erb
$("#task_<%= @task.id %>").fadeOut(500, function(){
	$(this).remove();
});

app/views/tasks/edit.html.erb
<h1 class="text-center">Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="row fundo">
      <div class="row">
        <div class="text-center">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                Launch New Modal
                New Post
            </button>
        </div>
    </div>
  <div class="col-md-4">
    <h1 class="text-center">Todo</h1>
    <div id="container_tasks">
      <%= render @to_do %>
    </div>
  </div>
  
  <div class="col-md-4">
    <h1 class="text-center">Doing</h1>
    <%= render @doing %>
  </div>
  
  <div class="col-md-4">
    <h1 class="text-center">Done</h1>
    <%= render @done %>
  </div>
  
</div>


</br>
<%= link_to 'New Task', new_task_path %>



  <!-- Modal -->
    <%= simple_form_for(@task, remote: true, html: { class:'form-signin'}  ) do |f| %>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">New Task</h4>
          </div>
          <div class="modal-body">
            <%= f.input :content, required: true, label: false, autofocus: true, placeholder: "Content", input_html: {class: 'form-control'} %>
          </div>
          <div class="modal-footer">
            <%= submit_tag "Create", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    </div>
    
  

app/views/tasks/new.html.erb
<h1 class="text-center">New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.state %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$("#myupdatetask_<%= @task.id %>").modal('hide');
$("#task_<%= @post.id %>").fadeOut(500, function(){
	$(this).remove();
	$("#container_tasks").prepend('<%= j render @task %>');